#pragma once

#define RTOS_STACK_SIZE 4096
#define ARDUINO_CORE 1
#define IO_CORE 0

#define CREATE_TASK_CORE(FUNC, NAME, PRIO, HANDLE, CORE) xTaskCreatePinnedToCore(FUNC, NAME, RTOS_STACK_SIZE, NULL, PRIO, HANDLE, CORE)
#define CREATE_TASK(FUNC, NAME, PRIO, HANDLE) CREATE_TASK_CORE(FUNC, NAME, PRIO, HANDLE, ARDUINO_CORE)
#define CREATE_TASK_IO(FUNC, NAME, PRIO, HANDLE) CREATE_TASK_CORE(FUNC, NAME, PRIO, HANDLE, IO_CORE)

bool safeRestart();
